import type { Metadata } from 'next'
import { createTheme, MantineProvider } from '@mantine/core'
import '@mantine/core/styles.css'
import './globals.css'

const theme = createTheme({
  /** Put your mantine theme override here */
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <MantineProvider theme={theme}>
        <body>{children}</body>
      </MantineProvider>
    </html>
  )
}
